spring:
  application:
    name: order-service
  datasource:
    password: pass@word1
    url: jdbc:mysql://localhost:3306/userdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  
server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost  